version: '3.8'

services:
  simple-config:
    build: .
    container_name: simple-config
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.simple-config.rule=Host(`config.subx.fun`)"
      - "traefik.http.routers.simple-config.entrypoints=websecure"
      - "traefik.http.routers.simple-config.tls=true"
      - "traefik.http.services.simple-config.loadbalancer.server.port=5173"
    networks:
      - traefik

networks:
  traefik:
    external: true
