version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - sqlite-data:/app/data
    env_file:
      - .env
    restart: unless-stopped

volumes:
  sqlite-data: 