version: '3.8'

services:
  envconfig:
    build: .
    container_name: envconfig
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.envconfig.rule=Host(`config.subx.fun`)"
      - "traefik.http.routers.envconfig.entrypoints=websecure"
      - "traefik.http.routers.envconfig.tls=true"
      - "traefik.http.routers.envconfig.tls.certresolver=letsencrypt"
      - "traefik.http.services.envconfig.loadbalancer.server.port=5173"
    networks:
      - traefik
    volumes:
      - /home/ubuntu/envconfig/db.json:/app/db.json

networks:
  traefik:
    external: true
